#pragma once

#define FIFO_Anhydrate_CAMERA1 "/tmp/Anhydrate/fifocam1"
#define FIFO_Anhydrate_AUDIO1 "/tmp/Anhydrate/fifoaudio1"
#define FIFO_Anhydrate_AUDIO_QUEUE "/tmp/Anhydrate/fifoaudioqueue"
#define FIFO_Anhydrate_AUDIO_BUFF "/tmp/Anhydrate/fifoaudiobuff"

// Must be same name used by video player when it's using fifo pipes
#define FIFO_Anhydrate_STATION_VIDEO_STREAM_DISPLAY "/tmp/Anhydrate/fifovideo_disp"
#define FIFO_Anhydrate_STATION_VIDEO_STREAM_RECORDING "/tmp/Anhydrate/fifovideo_rec"
#define FIFO_Anhydrate_STATION_VIDEO_STREAM_ETH "/tmp/Anhydrate/fifovideo_eth"

#define SEMAPHORE_RESTART_VIDEO_STREAMER "Anhydrate_SEM_RESTART_VIDEO_STREAMER"
#define SEMAPHORE_VIDEO_STREAMER_OVERLOAD "Anhydrate_SEM_VIDEO_STREAMER_OVERLOAD"

#define Anhydrate_SEM_RX_RADIO_HIGH_PRIORITY "Anhydrate_SEM_RX_RADIO_HIGH_PRIORITY"
#define Anhydrate_SEM_RX_RADIO_REG_PRIORITY "Anhydrate_SEM_RX_RADIO_REG_PRIORITY"

#define SEMAPHORE_SM_VIDEO_DATA_AVAILABLE "Anhydrate_SEM_SM_VIDEO_DATA_AVAILABLE"
#define SEMAPHORE_MPP_DISPLAY_FRAME_READY "Anhydrate_SEM_MPP_DISPLAY_FRAME_READY"
#define SEMAPHORE_MPP_DECODER_STALLED "Anhydrate_SEM_MPP_STALLED"
#define SEMAPHORE_MPP_DECODER_NO_NEW_OUTPUT "Anhydrate_SEM_MPP_NO_NEW_OUTPUT"

#define SEMAPHORE_RESTART_VEHICLE_PROCS "Anhydrate_SEM_RESTART_V_PROCS"
#define SEMAPHORE_STOP_VEHICLE_COMMANDS "Anhydrate_SEM_STOP_V_COMMANDS"
#define SEMAPHORE_STOP_VEHICLE_RC_RX "Anhydrate_SEM_STOP_V_RC_RX"
#define SEMAPHORE_STOP_VEHICLE_TELEM_TX "Anhydrate_SEM_STOP_V_TELEM_TX"
#define SEMAPHORE_STOP_VEHICLE_ROUTER "Anhydrate_SEM_STOP_V_ROUTER"

#define SEMAPHORE_SET_RADIO_TX_POWER "Anhydrate_SEM_SET_TX_POWER"
#define SEMAPHORE_SET_MAJESTIC_PARAMS_ASYNC "Anhydrate_SEM_SET_MAJ_ASYNC"

#define SEMAPHORE_WATCHDOG_CONTROLLER_PAUSE "Anhydrate_SEM_WD_CTRL_PAUSE"
#define SEMAPHORE_WATCHDOG_CONTROLLER_RESUME "Anhydrate_SEM_WD_CTRL_RESUME"
#define SEMAPHORE_WATCHDOG_CONTROLLER_RESTART "Anhydrate_SEM_WD_CTRL_RESTART"

#define SEMAPHORE_VIDEO_FILE_PLAYBACK_WILL_FINISH "Anhydrate_SEM_VIDEO_PLAY_WILL_FINISH"
#define SEMAPHORE_VIDEO_FILE_PLAYBACK_FINISHED "Anhydrate_SEM_VIDEO_PLAY_FINISHED"

